env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:astro/recommended
    - plugin:svelte/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
rules: {}
overrides:
    - files:
          - "*.astro"
      plugins:
          - astro
      env:
          node: true,
          astro/astro: true
          es2020: true
      parser: "astro-eslint-parser"
      parserOptions:
          parser: "@typescript-eslint/parser"
          extraFileExtensions:
              - ".astro"
          sourceType: "module"
      rules:
          astro/no-conflict-set-directives: "error"
          astro/no-unused-define-vars-in-style: "error"
    - files:
          - "**/*.astro/*.ts"
          - "*.astro/*.ts"
      env:
          browser: true
          es2020: true
      parser: "@typescript-eslint/parser"
      parserOptions:
          sourceType: "module"
          project: null
      rules:
          prettier/prettier: "off"
    - files:
          - "*.svelte"
      parser: "svelte-eslint-parser"
      parserOptions:
          ts: "@typescript-eslint/parser"
          typescript: "@typescript-eslint/parser"
