printWidth: 80
tabWidth: 4
useTabs: true
semi: true
singleQuote: false
plugins:
    - "prettier-plugin-astro"
    - "prettier-plugin-svelte"
overrides:
    - files: "*.svelte"
      options:
          parser: "svelte"
